name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-non-linux:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v ./...

  build-linux:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      CGO_ENABLED: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          go get ./...
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
          python -m pip install httpie

      - name: Build
        run: go build .

      - name: Go Test
        run: go test -v ./...

      - name: Spec Test
        run: |
          sudo cp goqoa /usr/bin/
          bash check_spec.sh

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-non-linux
      - build-linux
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev

      - name: Release Go binaries on tags
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
